name: Cypress Tests

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, feature/*]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Login: $LOGIN"
          echo "Password: $PASSWORD"
          npm run cypress:run -- --branch ${{ matrix.branch }}
